services:
  - postgresql
matrix:
  include:
    - language: elixir
      elixir:
        - '1.9.0'
        - '1.8.2'
      env:
        - MIX_ENV=test
      install:
        - mix local.rebar --force
        - mix local.hex --force
        - mix deps.get
      before_script:
        - psql -c 'CREATE DATABASE webcat_test; CREATE USER webcat WITH ENCRYPTED PASSWORD \'webcat\'; GRANT ALL PRIVILEGES ON DATABASE webcat_test TO webcat;'
        - mix ecto.setup
      script:
        - mix test
    - language: elm
      elm: 0.19.0
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
        - export PATH=$HOME/.yarn/bin:$PATH
      cache:
        yarn: true
      install:
        - yarn install
      before_script:
        - cd assets
      script:
        - yarn test

