service: api
env: flex
runtime: custom
beta_settings:
  cloud_sql_instances: "valid-reflector-214820:us-east1:webcat-primary"
liveness_check:
  path: "/healthcheck"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2