version: '3'

services:
  db:
    image: postgres:10.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=wcat
      - POSTGRES_PASSWORD=wcat
      - POSTGRES_DB=wcat
  web:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: /start.sh
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db