name: Haskell CI

# Trigger the workflow on push or pull request
on:
  pull_request:
  push:

jobs:
   stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.1.3"]
        ghc:
          - "8.6.5"
          - "8.8.3"
          - "8.10.1"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
    - uses: cachix/install-nix-action@v9
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc
